# ---
# This is an EXAMPLE configuration file. To run the pipeline on your own machine,
# make a copy named 'config.yml' and then change the paths & settings as needed.

# --------------------------------------------------
# PATHS

# paths the directories that contains raw data (i.e., not produced locally during pipeline run)
CIWQS_data_path: ~/sherlock_oak/EPA/Data/manual/california
ICIS_NPDES_data_path: ~/Documents/RegLab/projects/ca_mmp/policy_eval/ICIS-NPDES_data
CP_data_path: ~/Documents/RegLab/projects/ca_mmp/policy_eval/CP_data

# path to where plots should end up
plot_path: /Users/rtreves/Documents/RegLab/python_projects/ca_mmp/policy_eval/plots
# what dpi should the paper figures have?
figure_dpi: 600

# default:
#     DMRfraud.db_connection_file: "db_connection.yml"
#     DMRfraud.foreach_chunk_rate: 0.5
#     DMRfraud.log_debug_every:    1000
#     DMRfraud.parallel_nodes: !expr parallel::detectCores()-1
