---
title: "interstate_facility_comparison"
author: "Ryan Treves"
date: "2023-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F)
library(tidyverse)
library(yaml)
library(lubridate)
library(MatchIt)
require(dplyr)

# Retrieve data path
ICIS_NPDES_data_path = read_yaml('config.yml', eval.expr=TRUE)$ICIS_NPDES_data_path
```

```{r}
# Load data
exceedance_data_by_facility <- read_csv(paste0(ICIS_NPDES_data_path, '/exceedance_data_by_facility.csv'), col_types = cols(exceedance_rate = col_double())) %>% 
       mutate(year=year(year))
```

```{r}
# Preprocess data
data_pivoted <-  exceedance_data_by_facility %>%
  dplyr::select(permit_state, npdes_permit_id, year, parameter_category, mean_exceedance_pct_a) %>%
  filter(year<2008, parameter_category %in% c('Pathogens', 'Ammonia', 'Solids')) %>%
  dplyr::select(permit_state, npdes_permit_id, parameter_category, year, 
         mean_exceedance_pct_a) %>% 
  pivot_wider(id_cols=c('permit_state',
                        'npdes_permit_id'),
                        names_from=c('parameter_category', 'year'), values_from=c('mean_exceedance_pct_a')) %>%
  mutate(treat=ifelse(permit_state=='CA', 1, 0)) %>%
drop_na()
```

```{r}
# Match exceedance data series
m.out <- mmatcher(ds=as.data.frame(data_pivoted),
                   group_var='treat', x_vars=colnames(data_pivoted %>% dplyr::select(-c('permit_state', 'npdes_permit_id', 'treat'))),
                   id_var='npdes_permit_id')
```

```{r}
exceedance_data_by_facility %>%
  filter(npdes_permit_id %in% c('CA0047899', 'NH0101257'),
         parameter_category %in% c('Ammonia', 'Pathogens', 'Solids')) %>%
  ggplot()+
  geom_line(aes(x=year, y=mean_exceedance_pct_a, color=npdes_permit_id))+
  facet_wrap(vars(parameter_category), scales='free', nrow=2)+
  theme_minimal()
```
```{r}
exceedance_data_by_facility %>%
  filter(npdes_permit_id %in% c('CA0048160', 'UT0024392'),
         parameter_category %in% c('Ammonia', 'Pathogens', 'Solids')) %>%
  ggplot()+
  geom_line(aes(x=year, y=mean_exceedance_pct_a, color=npdes_permit_id))+
  facet_wrap(vars(parameter_category), scales='free', nrow=2)+
  theme_minimal()
```
