---
title: "DiD Analysis - Facility Level"
output: html_document
date: "2022-12-1"
---

```{r}
library(readr)
library(tidyverse)
library(fixest)
```

```{r}
# Read in and clean data
data <- read_csv("violations_to_analyze_facility_level_yearly.csv")
data <- select(data, -...1)
data$Region <- as.factor(data$Region)

# Restrict our analysis to 4 years pre/post treatment, optional
data <- filter(data, violation_period < 2013) %>% filter(violation_period > 2003)
```


```{r}
# Change violation year to be categorical
data$violation_period <- as.factor(data$violation_period)
```

Linear probability model on violation status
```{r}
model.fit <- feols(violation_status ~ treatment*post | Region + violation_period, data=data)
```

```{r}
dynamic_model.fit <- feols(violation_status ~ i(violation_period, treatment, ref=2008) | Region + violation_period,
      data=data)
iplot(dynamic_model.fit)
```

```{r}
etable(list(model.fit, dynamic_model.fit))
```

Negative binomial regression on number of violations
```{r}
mean(data$n_violations)
var(data$n_violations)
```

Because the mean and variance are so different, it's likely more appropriate
to fit a negative binomial regression:
```{r}
# Offset negative binomial models
negbin_fit_offset <- fenegbin(n_violations ~ treatment + I(treatment*post) + offset(log(n_values_permit_period)) | Region + violation_period, data=data)
```
```{r}
negbin_fit_offset_dynamic <- fenegbin(n_violations ~ i(violation_period, treatment, ref=2008) + offset(log(n_values_permit_period)) | Region + violation_period,
      data=data)
iplot(negbin_fit_offset_dynamic)
```
```{r}
etable(list(negbin_fit_offset, negbin_fit_offset_dynamic))
```
```{r}
# Non-offset Negative binomial models
negbin_fit <- fenegbin(n_violations ~ treatment*post | Region + violation_period, data=data)
```

```{r}
negbin_fit_dynamic <- fenegbin(n_violations ~ i(violation_period, treatment, ref=2008) | Region + violation_period,
      data=data)
iplot(negbin_fit_dynamic)
```