---
title: "Case Study Selection Figure"
author: "Ryan Treves"
date: "2023-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
library(tidyverse)
library(yaml)
library(lubridate)
library(zoo)
library(ggrepel)
library(readxl)
```

```{r}
# Retrieve data
CP_data_path = read_yaml('config.yml', eval.expr=TRUE)$CP_data_path
# Specify visual parameters for figures
preset_dpi <-  read_yaml('config.yml', eval.expr=TRUE)$figure_dpi

# Get data on CP eligibility
CP_data <- read_csv(paste0(CP_data_path, '/POTW_service_area_2010.csv'))

# Load in violations data
violations <- read_excel(paste0(CIWQS_data_path, '/violations_export_2021-10-26.xlsx')) %>%
  mutate(FACILITY_ID=as.character(FACILITY_ID),
         `VIOLATION ID (VID)`=as.character(`VIOLATION ID (VID)`)) %>%
  # We only want POTWs and effluent violations
  filter(`PLACE SUBTYPE`=='Wastewater Treatment Facility',
          `VIOLATION TYPE`=='Effluent',
         `STATUS...79` != 'Dismissed',
         (!str_detect(`VIOLATION COMMENTS`, 'In compliance') | 
            is.na(`VIOLATION COMMENTS`)),
         (!str_detect(`CORRECTIVE ACTION`, 'In compliance') | 
            is.na(`CORRECTIVE ACTION`))) %>%
  # Select only useful columns
  select(`VIOLATED FACILITY REGION`, FACILITY_ID, `FACILITY NAME`, `PLACE SUBTYPE`,
         `FACILITY TYPE`, `DESIGN FLOW`, `NPDES# CA#`, `VIOLATION ID (VID)`,
         `VIOLATION DESCRIPTION`, `VIOLATION COMMENTS`, `CORRECTIVE ACTION`,
         `OCCURRED ON`) %>%
  # Drop violations with missing facility ID
  drop_na(FACILITY_ID)

# Enforcement data
enforcements <- read_csv(paste0(CIWQS_data_path, '/enf_actions_export.csv'),
                         col_types = cols(`FACILITY ID` = col_character(), 
        `ENFORCEMENT ID (EID)` = col_character())) %>%
        rename(FACILITY_ID=`FACILITY ID`)
```

```{r}
# Data cleaning
enforcements <- enforcements %>%
  # We want MMP-related enforcement actions on POTWs with penalties
  filter(`TOTAL MMP VIOLATIONS #`>0,
         (`LIABILITY $ AMOUNT`>0 | `TOTAL ASSESSMENT AMOUNT`>0),
         `PLACE SUBTYPE`=='Wastewater Treatment Facility',
         `STATUS...82` != 'Draft') %>%
  select(`REGION...1`, FACILITY_ID, `FACILITY NAME`,
         `ENFORCEMENT ID (EID)`, `ORDER / RESOLUTION NUMBER`,
         `ENFORCEMENT ACTION TYPE`, `EFFECTIVE DATE...76`, `ADOPTION / ISSUANCE DATE`,
         `ACL ISSUANCE DATE`, `EPL ISSUANCE DATE`, `STATUS...82`, `DESCRIPTION`,
         `TOTAL ASSESSMENT AMOUNT`, `INITIAL ASSESSED AMOUNT`, `LIABILITY $ AMOUNT`,
         `LIABILITY $ PAID`, `TOTAL $ PAID/COMPLETED AMOUNT`) %>%
  rename(`EFFECTIVE DATE`=`EFFECTIVE DATE...76`,
         `REGION`=`REGION...1`,
         `STATUS`=`STATUS...82`) %>%
  mutate(`EFFECTIVE DATE`=mdy(`EFFECTIVE DATE`),
         `ADOPTION / ISSUANCE DATE`=mdy(`ADOPTION / ISSUANCE DATE`),
         `ACL ISSUANCE DATE`=mdy(`ACL ISSUANCE DATE`),
         `EPL ISSUANCE DATE`=mdy(`EPL ISSUANCE DATE`)) %>% 
  # Estimate the date of an enforcement action
  rowwise() %>%
  mutate(min_issuance_date=min(`ACL ISSUANCE DATE`, `EPL ISSUANCE DATE`, na.rm=T)) %>%
  mutate(min_issuance_date=na_if(min_issuance_date, Inf)) %>%
  mutate(estimated_date=coalesce(min_issuance_date, `EFFECTIVE DATE`)) %>%
  mutate(estimated_year=year(estimated_date))
```

Analysis

First: distance to CP eligibility boundary
```{r}
# Data point on state median income in 2008 from US fed: https://fred.stlouisfed.org/series/MEHOINUSCAA646N
CP_data <- CP_data %>%
  # Standardize population and income
  mutate(tot_pop_standardized=tot_pop/10000, 
         median_inc_standardized=median_inc/57014) %>%
  # Experimenting with logging population
  mutate(tot_pop_logged=log10(tot_pop)/log10(10000)) %>%
  mutate(distance_to_2008_boundary=ifelse(median_inc_standardized < 1 | tot_pop_standardized <= 1, pmax(tot_pop_standardized-1, median_inc_standardized-1),
                                          sqrt((median_inc_standardized-1)^2 + (tot_pop_standardized-1)^2)),
         distance_to_2008_boundary_2=ifelse(median_inc_standardized < 1 | tot_pop_logged <= 1, pmax(tot_pop_logged-1, median_inc_standardized-1),
                                          sqrt((median_inc_standardized-1)^2 + (tot_pop_logged-1)^2))) %>%
  mutate(distance_percentile=rank(distance_to_2008_boundary_2)/n())
```

Next: change in compliance pre/post enforcement


```{r}
enforcement_years <- enforcements %>%
  full_join(tibble(FACILITY_ID=sort(rep((unique(enforcements$FACILITY_ID)), 21)),
                   estimated_year=rep(seq(2000,2020), length(unique(enforcements$FACILITY_ID)))), by=c('estimated_year','FACILITY_ID')) %>%
  group_by(FACILITY_ID, estimated_year) %>%
  summarize(n_enforcements=n_distinct(`ENFORCEMENT ID (EID)`, na.rm=T),
            total_penalized=sum(`TOTAL ASSESSMENT AMOUNT`, na.rm=T))

violations_by_year <- violations %>% 
  mutate(estimated_year=year(`OCCURRED ON`)) %>%
  full_join(tibble(FACILITY_ID=sort(rep((unique(violations$FACILITY_ID)), 21)),
                   estimated_year=rep(seq(2000,2020), length(unique(violations$FACILITY_ID)))), by=c('estimated_year','FACILITY_ID')) %>%
  group_by(FACILITY_ID, `NPDES# CA#`, estimated_year) %>%
  summarize(n_violations=n_distinct(`VIOLATION ID (VID)`, na.rm=T))

violations_by_year <- enforcement_years %>%
  full_join(violations_by_year, by=c('FACILITY_ID', 'estimated_year'))

# Over how many years to average violation counts. Enforcement year is included in
# pre-window.
window_length <- 4

pre_post_change_by_fac <- violations_by_year %>%
  group_by(FACILITY_ID, `NPDES# CA#`) %>%
  # Calculate rolling averages of violation counts pre/post enforcement
  mutate(violations_pre=rollmean(lag(n_violations, 2), window_length, fill=NA, align='right'),
         violations_post=rollmean(lead(n_violations, 2), window_length, fill=NA, align='left')) %>%
  # Calculate change in violation number pre/post enforcement
  mutate(pre_post_change=(violations_post-violations_pre)) %>%
  # Only retain stats from enforcement years
  filter(n_enforcements>0) %>%
  # Drop rows for which complete pre/post data is not available
  drop_na() %>%
  # For each facility, average the changes across all enforcements
  summarize(mean_pre_post_change=mean(pre_post_change),
            pre_post_first_enforcement_year=first(pre_post_change, order_by=estimated_year),
            pre_post_largest_enforcement_year=last(pre_post_change, order_by=total_penalized),
            mean_violations_pre_median=median(violations_pre),
            violations_pre_first_enforcement_year=first(violations_pre, order_by=estimated_year),
            violations_pre_largest_enforcement_year=last(violations_pre, order_by=total_penalized))
```


```{r}
to_plot <- pre_post_change_by_fac %>%
  rename(npdes_permit_id=`NPDES# CA#`) %>%
  inner_join(CP_data, by='npdes_permit_id') %>%
  filter(!npdes_permit_id %in% c('CA0056227', 'CA0078093'))

case_studies <- c('CA0047953', 'CA0048151',
                           'CA0079529', 'CA0081621')

to_plot %>%
  filter(violations_pre_first_enforcement_year >= 5) %>%
  ggplot(aes(x=pre_post_first_enforcement_year, y=distance_to_2008_boundary_2))+
  stat_density_2d(aes(fill=..level..), geom='polygon', alpha=0.5)+
  scale_fill_distiller(palette=1, direction=1)+
  geom_point(data=to_plot %>% filter(npdes_permit_id %in% case_studies), size=2.5)+
  geom_text_repel(data=to_plot %>% filter(npdes_permit_id %in% case_studies) %>%
                    mutate(facility_name=ifelse(facility_name == 'Paso Robles WWTP', 'Paso Robles',
                                                ifelse(facility_name == 'Pismo Beach WWTP', 'Pismo Beach',
                                                       ifelse(facility_name == 'City of Colfax WWTP', 'Colfax',
                                                              'Donner Summit')))),
                  aes(label=ifelse(npdes_permit_id %in% case_studies, facility_name, NA)), size=5, color='black')+
  geom_hline(aes(yintercept=0), color='gray', linetype='dashed')+
  labs(x='Change in mean annual # violations pre/post first MMP penalty', y='Distance outside penalty conversion eligibility cutoffs')+
  scale_y_continuous(breaks=0, limits=c(-0.5, 1.2))+
  xlim(-50, 50)+
  theme_minimal()+
  theme(legend.position='none')
ggsave('fig_case_study_selection.png', width=3600, height=2400, units='px',
       bg='white', dpi=preset_dpi)
```
