---
title: "summary_stats"
author: "Ryan Treves"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F)
library(tidyverse)
library(yaml)
library(lubridate)
```

```{r, warning=F}
# Retrieve data paths
ICIS_NPDES_data_path = read_yaml('config.yml', eval.expr=TRUE)$ICIS_NPDES_data_path
```

```{r}
# Load data
exceedance_data <- read_csv(paste(ICIS_NPDES_data_path,
                                                    'exceedance_data_yearly_1000.csv',
                                         sep='/')) %>%
  mutate(year=year(monitoring_period)) %>%
  filter(year >= 2004)
```

```{r}
summary_data <- exceedance_data %>%
  filter(is.na(parameter_category),
         permit_state=='CA',
         (facility_type_indicator=='POTW'))  %>%
  select(year, n_dmrs, n_exceedances, n_permittees)
```

```{r}
# Save summary data
write_csv(summary_data, paste(ICIS_NPDES_data_path, 'summary_table.csv',
                              sep='/'))
```

