---
title: "Untitled"
author: "Ryan Treves"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(yaml)
# Data source: https://app.mode.com/editor/reglab/reports/aad9ee3f0964/queries/e716aa3a6bc1
ICIS_NPDES_data_path = read_yaml('../config.yml', eval.expr=TRUE)$ICIS_NPDES_data_path
exceedance_data <- read_csv(paste(ICIS_NPDES_data_path,
                                                    'exceedance_data_yearly_1000.csv',
                                         sep='/'), 
    col_types = cols(frac_any_exceedance = col_double(),
                     frac_any_exceedance_20pct = col_double(),
                     frac_any_exceedance_40pct = col_double(),
                     avg_exceedance_rate = col_double(),
                     avg_exceedance_20pct_rate = col_double(),
                     avg_exceedance_40pct_rate = col_double(),
                     mean_days_late = col_double())) %>%
  replace_na(list(facility_type_indicator='All', parameter_category='All')) %>%
  mutate(year=year(year))
```

```{r}
CA_yearly_table <- exceedance_data %>%
  filter(parameter_category=='All') %>%
  mutate(pre_2008=ifelse(year<2008, 'pre_2008', 'post_2008'),
         donor_pool=ifelse(permit_state=='CA', 'CA treatment regions', 'Donor pool states')) %>%
  group_by(pre_2008, donor_pool) %>%
  summarize(mean_n_POTWs=round(mean(n_permittees, na.rm = T)), 
            mean_n_dmrs=round(mean(n_dmrs, na.rm=T)),
            mean_n_exceedances=round(mean(n_exceedances, na.rm=T)),
            mean_days_late=round(mean(mean_days_late, na.rm=T), 2)) %>%
  arrange(donor_pool, desc(pre_2008))
View(CA_yearly_table)
```

```{r}
CA_agg_table <- exceedance_data %>%
  filter(permit_state=='CA',
         parameter_category=='All') %>%
  mutate(frac_avg=n_avg/n_dmrs, frac_min=n_min/n_dmrs, frac_max=n_max/n_dmrs,
         frac_monthly=n_monthly/n_dmrs, frac_quarterly=n_quarterly/n_dmrs,
         frac_semiannual=n_semiannual/n_dmrs, frac_annual=n_annual/n_dmrs) %>%
  select(frac_avg, frac_min, frac_max, frac_monthly, frac_quarterly, frac_semiannual,
         frac_annual, min_actual_average_flow_nmbr, med_actual_average_flow_nmbr,
         max_actual_average_flow_nmbr)
CA_agg_table <- CA_agg_table%>%
  summarize(variable=colnames(CA_agg_table),
            `mean_2004-2016`=round(colMeans(.), 2))
View(CA_agg_table)
```

```{r}
write_csv(CA_agg_table, 'summary_stats.csv')
```
