---
title: "region_level_analysis"
output:
  pdf_document: default
  html_document: default
date: "2022-10-28"
---

```{r, echo=F, message=F}
library(tidyverse)
library(readr)
library(fixest)

# Read in and clean data
viols <- read_csv('viols_preprocessed.csv', col_types = cols(Region = col_character()))
viols <- select(viols, -...1)
```


```{r}
# Fit linear model to estimate average treatment effect on 
# violation rate. I'm using `fixest::feols` instead of `lm` because
# the model output is easier to display - but the model fit is the same.
model.fit <- feols(violation_rate ~ treatment*post, data=filter(viols, (violation_year > 2003) & (violation_year < 2013)))
```

```{r}
# Fit linear model to estimate the year-by-year dynamic treatment effect on
# violation, restricting time range to 2004-2012
dynamic_model.fit <- feols(violation_rate ~ i(violation_year, treatment, ref=2008), data=filter(viols, (violation_year > 2003) & (violation_year < 2013)))
```

```{r}
iplot(dynamic_model.fit)
etable(list(model.fit, dynamic_model.fit))
```

Writing out model equations: 
Model 1:
$$y_{it} = \beta_0 + \beta_1Z_i+\beta_2P_t+\beta_3Z_iP_t + \epsilon_{it}$$
Model 2:
$$y_{it} = \beta_0 + \alpha_i + \delta_t + \sum_{k=2004}^{2007}\beta_kZ_{i}\mathbf{1}[t=k] + \sum_{k=2009}^{2012}\beta_kZ_{i}\mathbf{1}[t=k] + \epsilon_{it}$$


